### ISSUE TITLE
Quality flags

### ISSUE THREAD

**Issue by bpbond** [COMPASS-DOE/COMPASS-synthesis#18]
Filter out SRDB entries with non-NA quality flags.

**Comment by stephpenn1** [comment]
@bpbond Which quality flags do we want to exclude from `srdb`? Here's a rough distribution of them
![image](https://user-images.githubusercontent.com/20341158/109541120-6e0b1a00-7a91-11eb-8dad-6e3bc461c581.png)


![Screen Shot 2021-03-01 at 1 13 36 PM](https://user-images.githubusercontent.com/20341158/109540225-2cc63a80-7a90-11eb-9363-f368bd67759f.png)

**Comment by bpbond** [comment]
I think any of the double-digit ones (Q10-Q15) should be filtered out. The others seem OK though.
