### ISSUE TITLE
Include Rh_annual and Rs_growing season

### ISSUE THREAD

**Issue by stephpenn1** [COMPASS-DOE/COMPASS-synthesis#23]

**Comment by stephpenn1** [comment]
@bpbond I don't remember exactly what this was referring to

**Comment by bpbond** [comment]
Right now we are doing the processing and graph for only one _dependent variable_, `Rs_annual` (total annual soil respiration). But we'll also want to make similar computations, based on the data Shoshi has now finished entering in the Google Sheet, for `Rh_annual` (total heterotrophic respiration) and `Rs_growingseason` (mean growing season soil respiration) as well.
