### ISSUE TITLE
SP update 3/7

### ISSUE THREAD

**Issue by stephpenn1** [COMPASS-DOE/COMPASS-synthesis#25]
Hello @bpbond hope you had a swell weekend,

I've gone through most of #21 and am looking through the `metafor` documentation now (will put more thoughts on it in this issue later).

This week I'll be working on: 
- running the analysis with shoshi's updated data
- #23 
- maybe testing some metafor functions with our data

Questions: 
- What should our next steps be in terms of analysis? Do we want to use a statistical model with effect size?

**Comment by bpbond** [comment]
Thank you @stephpenn1 — the update is much appreciated.

Re next steps, I have a proposal was going to lay out in our meeting with Shoshi but unfortunately that's not until Friday now. Suggestion is we have two tracks:
1. Implement a fixed-effects meta-analysis, maybe first by hand (following that YouTube video!) and/or using `metafor`
2. Implement a correction for differing irrigation levels, perhaps following the Liu et al. (2016) one

**Comment by bpbond** [comment]
Just noting: this paper has a clear description of their meta-analysis steps and is similar in many ways to ours (but different area of research).
