### ISSUE TITLE
SP Synthesis 3/22

### ISSUE THREAD

**Issue by stephpenn1** [COMPASS-DOE/COMPASS-synthesis#27]
- [x] Integrate `metafor.Rmd` and `rs-synthesis.Rmd` to resolve #23 
- [x] Set up folder for Shoshi to go through the 2018+ Rs studies
- [x] Inventory PR
- [x] Help Shoshi get started on data entry for the new studies

**Comment by bpbond** [comment]
One thing we didn't mention this morning: will you have time to finish the [inventory update](https://github.com/COMPASS-DOE/TEMPEST/pull/22)? That's a fairly high priority imho.

**Comment by stephpenn1** [comment]
This is up to date as of 3/29. Will work on the first task this week and hopefully get Shoshi running with data entry for the 2018+ studies
